# Generated by Django 5.2.7 on 2025-10-08 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_id', models.CharField(max_length=64, unique=True)),
                ('release_date', models.DateField()),
                ('genre', models.CharField(max_length=100)),
                ('distributor', models.CharField(max_length=255)),
                ('entertainment', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.CharField(max_length=64, unique=True)),
                ('singer', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('genre', models.CharField(max_length=100)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='hitmakers.album')),
            ],
        ),
        migrations.CreateModel(
            name='SongCreator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('composer', 'Composer'), ('lyricist', 'Lyricist'), ('arranger', 'Arranger')], max_length=20)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_songs', to='hitmakers.creator')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_creators', to='hitmakers.song')),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='creators',
            field=models.ManyToManyField(related_name='songs', through='hitmakers.SongCreator', to='hitmakers.creator'),
        ),
        migrations.CreateModel(
            name='YearlyChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True)),
                ('rank', models.IntegerField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_charts', to='hitmakers.album')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_charts', to='hitmakers.song')),
            ],
        ),
        migrations.AddConstraint(
            model_name='songcreator',
            constraint=models.UniqueConstraint(fields=('song', 'creator', 'role'), name='unique_song_creator_role'),
        ),
        migrations.AddIndex(
            model_name='yearlychart',
            index=models.Index(fields=['year', 'rank'], name='hitmakers_y_year_0b0d4f_idx'),
        ),
        migrations.AddIndex(
            model_name='yearlychart',
            index=models.Index(fields=['year', 'song'], name='hitmakers_y_year_331236_idx'),
        ),
        migrations.AddConstraint(
            model_name='yearlychart',
            constraint=models.UniqueConstraint(fields=('year', 'song'), name='unique_year_song'),
        ),
    ]
