# Generated by Django 5.2.6 on 2025-10-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenreCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=20)),
                ('genre_count', models.IntegerField()),
                ('season', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SongImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=100)),
                ('album_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TopSongs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=100)),
                ('song_name', models.CharField(max_length=100)),
                ('chart_count', models.IntegerField()),
                ('season', models.CharField(max_length=10)),
            ],
        ),
    ]
